### ISSUE TITLE
crash because of the xp obelisk

### ISSUE THREAD

**Issue by Lni-Energy-dev** [Meridanus/fabric_xp_storage_1.18#22]
I am playing All of Fabric 5

I have a deployer from Create, which consumes these xp thingies to Create xp orbs. The xp obelisk is set to suck in all xp orbs (right click with a redstone torch).

Whenever I load the world, it crashes with this error:
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/7/22, 9:23 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Amount may not be negative, but it is: -810
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:59)
	at com.notker.xp_storage.blocks.StorageBlockEntity$1.insert(StorageBlockEntity.java:59)
	at com.notker.xp_storage.blocks.StorageBlockEntity$1.insert(StorageBlockEntity.java:45)
	at com.notker.xp_storage.blocks.StorageBlockEntity.lambda$tick$0(StorageBlockEntity.java:197)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.notker.xp_storage.blocks.StorageBlockEntity.tick(StorageBlockEntity.java:194)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:59)
	at com.notker.xp_storage.blocks.StorageBlockEntity$1.insert(StorageBlockEntity.java:59)
	at com.notker.xp_storage.blocks.StorageBlockEntity$1.insert(StorageBlockEntity.java:45)
	at com.notker.xp_storage.blocks.StorageBlockEntity.lambda$tick$0(StorageBlockEntity.java:197)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.notker.xp_storage.blocks.StorageBlockEntity.tick(StorageBlockEntity.java:194)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)

-- Block entity being ticked --
Details:
	Name: xps:entity_xp_obelisk // com.notker.xp_storage.blocks.StorageBlockEntity
	Block: Block{xps:block_xp_obelisk}[charged=true,facing=north,waterlogged=false]
	Block location: World: (-3818,100,1840), Section: (at 6,4,0 in -239,6,115; chunk contains blocks -3824,0,1840 to -3809,255,1855), Region: (-8,3; contains chunks -256,96 to -225,127, blocks -4096,0,1536 to -3585,255,2047)
	Block: Block{xps:block_xp_obelisk}[charged=true,facing=north,waterlogged=false]
	Block location: World: (-3818,100,1840), Section: (at 6,4,0 in -239,6,115; chunk contains blocks -3824,0,1840 to -3809,255,1855), Region: (-8,3; contains chunks -256,96 to -225,127, blocks -4096,0,1536 to -3585,255,2047)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 1727
	Level dimension: simplevoidworld:void
	Derived: true
	Level spawn location: World: (0,92,0), Section: (at 0,12,0 in 0,5,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 22186711 game time, 23757365 day time
	Level name: myworld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 10025 (now: false), thunder time: 593 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by Meridanus** [comment]
Thanks for the bug report.
I'll take a look and try to fix it. 

Occur the crash only on multiplayer /single player?

Can you provide the save file?
So i can try it on your world and see what the ide spits out.

**Comment by Lni-Energy-dev** [comment]
It happened on a multiplayer server. I downloaded the world to Singleplayer and it happend there too. 

I uploaded the world to google drive: [https://drive.google.com/file/d/1KoFcPMeRQKCTuqlsLkJGx0bvpyDJrGvC/view?usp=sharing](https://drive.google.com/file/d/1KoFcPMeRQKCTuqlsLkJGx0bvpyDJrGvC/view?usp=sharing)

The xp obelisk should be at **-3817 101 1840** in the **void dimension**. You will probably be there in Singleplayer when you load the world.

In case you are not there go to the same coordinates in the overworld and place "Portal to the void" from the mod "Simple Void World". Some chunks there are also claimed with ftbteams, and you might not be able to place, destroy or interact with blocks, if that is the case, you can just go one or two chunks to the side and place the portal there.

The chunk, which contains the xp obelisk is also chunk loaded with ftbteams, but I do not know if that also works in S
singleplayer...

**Comment by Lni-Energy-dev** [comment]
There is another thing I forgot to mention: AOF5 uses Xp Obelisk version `0.4.1.r_for_1.18.x_Fabric`. This is an old version. Maybe you have already fixed this issue. If this is the case, I am very sorry.

**Comment by Lni-Energy-dev** [comment]
okay thank you. The other crash is caused by A Vacuum Hopper and the Magnet from an AE2 Addon. They probably both try to suck in the same Item. I usually turn of the Magnet from the AE2 Addon before I go there.
